### PR TITLE
Docs/added learn 

### PR DESCRIPTION
**Pull request by Sibam-Paul**
Closes - #3 

@Harish-2003 **Please review my PR under wob'24**

### CODE REVIEW

**Comment by Harish-2003** [comment]
State that u need to follow the organisation and star the repo

**Comment by Sibam-Paul** [comment]
image
image

@Harish-2003 Can u please also add hacktoberfest along with wob'24 as I am also participating in it . It would be helpful for me

thanks :)

**Comment by Harish-2003** [comment]
> image
> image
> 
> @Harish-2003 Can u please also add hacktoberfest along with wob'24 as I am also participating in it . It would be helpful for me
> 
> thanks :)
> 

I am asking u to mention that statement in the learn.md file

**Comment by Sibam-Paul** [comment]
ok

**Review by Harish-2003 — APPROVED** [review]

**Comment by Sibam-Paul** [comment]
@Harish-2003 Please add labels , wob, level 2, heacktoberfest and assign me this PR please

**Comment by Sibam-Paul** [comment]
@Harish-2003 please assign and give labels or else it won't be counted

**Pull request merged**
