### PR TITLE
#Add Github Greetings Bot

### LINKED ISSUE #11: Add github greetings bot

### PR DESCRIPTION
**Pull request by KiranBaliga**
closes #11 

The YML file has been reviewed, tested with duplicate branches, Pull Requests and workflows were successful. Triggered greetings for PR and received emails. 

Please review and share the feedback.

### CODE REVIEW

**Comment by KiranBaliga** [comment]
@Harish-2003 please review and share feedback. Thank you!

**Comment by Harish-2003** [comment]
Will it works every time when people raise an issue raise an pr?

**Comment by Harish-2003** [comment]
The checks have Bern failed kindly check

**Comment by KiranBaliga** [comment]
@Harish-2003 I have modified the script. I had added additional messages for  additional actions but now I understood it needs seperate workflows. Please review.

**Review by Harish-2003 — APPROVED** [review]

**Pull request merged**
