### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by neeru24**
Hi,
I've updated the Readme file.
Kindly Merge my pull request.

Fixes: #30

### CODE REVIEW

**Comment by Harish-2003** [comment]
Can u send me the screenshot of how it looks

**Comment by neeru24** [comment]
> Can u send me the screenshot of how it looks

Screenshot 2024-10-03 110134
image
image

**Comment by Harish-2003** [comment]
Can u also add an statement to star the repo and follow openetekhub

**Comment by neeru24** [comment]
> Can u also add an statement to star the repo and follow openetekhub

Sure, Let me do so

**Comment by neeru24** [comment]
> Can u also add an statement to star the repo and follow openetekhub

Done ✅

**Review by Harish-2003 — APPROVED** [review]

**Pull request merged**
